In [1]:
# Voici une série de données concernant des astéroïdes
# ["nom de l'astéroïde", magnitude, nombre de lettres dans le nom]

asteroides = [
    ["Niobe", 8.5, 5],
    ["Feronia", 10.3, 7],
    ["Klytia", 10.3, 6],
    ["Galatea", 10.1, 7],
    ["Eurydike", 10.0, 8],
    ["Freia", 9.0, 5],
    ["Frigga", 9.6, 6],
    ["Diana", 9.1, 5],
    ["Eurynome", 9.3, 8],
    ["Sappho", 9.3, 6],
    ["Terpsichore", 9.7, 11],
    ["Alkmene", 9.4, 7]
]

# On souhaite calculer le coefficient de corrélation entre le nombre de lettres
# et la magnitude.
# On pourra utiliser numpy.corrcoeff ou le faire à partir des formules du cours.



In [2]:
import numpy as np

In [4]:
asteroides = np.array(asteroides)

In [32]:
nombre_lettres = asteroides[:,2].astype('int')
magnitude = asteroides[:,1].astype('float')

In [40]:
np.corrcoef(X)

array([[1.        , 0.41480808],
       [0.41480808, 1.        ]])

In [35]:
X = np.stack((magnitude, nombre_lettres), axis=0)
X

array([[ 8.5, 10.3, 10.3, 10.1, 10. ,  9. ,  9.6,  9.1,  9.3,  9.3,  9.7,
         9.4],
       [ 5. ,  7. ,  6. ,  7. ,  8. ,  5. ,  6. ,  5. ,  8. ,  6. , 11. ,
         7. ]])

In [44]:
covar = np.cov(X)
covar

array([[0.31      , 0.39545455],
       [0.39545455, 2.93181818]])

In [45]:
var_magnitude, var_nombre_lettres = np.var(X[0]), np.var(X[1])
var_magnitude, var_nombre_lettres

(0.28416666666666673, 2.6875)

In [28]:
b = np.var(asteroides[:,2].astype('int')) ,np.var(asteroides[:,1].astype('float'))
b

(2.6875, 0.28416666666666673)

In [39]:
covar / np.sqrt(var_magnitude)*np.sqrt(var_nombre_lettres)

array([[0.9533434 , 1.21614187],
       [1.21614187, 9.01622423]])

In [42]:
??np.cov