In [10]:
import numpy as np

In [12]:
tableau = np.array([i-i for i in range(0,10)])
tableau

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [17]:
np.ones(100, dtype='int8')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [18]:
np.repeat(np.array([1]), 100)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.full(100,1,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.array([i for i in range(101)])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
np.arange(0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [29]:
??np.ndarray

In [44]:
np.ndarray((10,10), buffer=np.array([i for i in range(1,101)]), dtype='int')

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [49]:
np.ndarray((10,10), buffer=np.arange(1,101), dtype='int')

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [47]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [131]:
np.eye(8, k=0)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [130]:
# list des éléments de 0 à 9:
x = np.arange(10)
print(x)
# selection les éléments de 5 à 9:
x[5:len(x):1]

[0 1 2 3 4 5 6 7 8 9]


array([5, 6, 7, 8, 9])

## Challenge
---
output of code:
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [121]:
#import numpy as np
x = np.zeros((8,8), int)
for j in [0,2]: # for rotation matrix, 0 for remain matrix, 2 to rotation 180 degree
    x = np.rot90(x,j)
    for i in [1,3,5,7]: # la matrix symétrique
        y = np.ones(8-i) # select numbre of element to create 1D matrix to replace diagonal x
        np.fill_diagonal(x[i:], y)
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [123]:
board = np.zeros((8,8), np.int32)
for ri in range(8):
   for ci in range(8):
     if (ci + ri+1) % 2 == 0:
       board[ri,ci] = 1
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

## Solution using slicing

In [138]:
board = np.zeros((8,8))
board[::2, 1::2] = 1
board[1::2, ::2] = 1
board

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#    **Numpy broadcasting:**

In [137]:
np.arange(5)*2

array([0, 2, 4, 6, 8])

In [139]:
np.arange(100).reshape((10,10)) + 1 * 2

array([[  2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48,  49,  50,  51],
       [ 52,  53,  54,  55,  56,  57,  58,  59,  60,  61],
       [ 62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81],
       [ 82,  83,  84,  85,  86,  87,  88,  89,  90,  91],
       [ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101]])

# random:

In [143]:
np.random.random((100)).reshape((10,10))

array([[0.90790941, 0.3547955 , 0.35779747, 0.56577895, 0.11548699,
        0.52851077, 0.08134838, 0.1403904 , 0.40862831, 0.61997907],
       [0.85627293, 0.94854191, 0.40580139, 0.45252795, 0.7967954 ,
        0.78283518, 0.28246838, 0.75743982, 0.42983366, 0.56913762],
       [0.94354077, 0.13237311, 0.51933085, 0.74621614, 0.7073289 ,
        0.62266593, 0.01943501, 0.14084266, 0.2507385 , 0.53669096],
       [0.82473069, 0.49359574, 0.79056537, 0.88377041, 0.96338291,
        0.14786457, 0.39722967, 0.29945966, 0.67479573, 0.46224037],
       [0.33840332, 0.96166291, 0.10378358, 0.91906371, 0.79127726,
        0.53770508, 0.53820938, 0.81307568, 0.38683299, 0.23679769],
       [0.23894717, 0.67086348, 0.33444226, 0.80081468, 0.55651859,
        0.87931326, 0.187153  , 0.16331487, 0.0502451 , 0.27252189],
       [0.92439754, 0.42335809, 0.71206644, 0.01313731, 0.14309985,
        0.54618627, 0.87556108, 0.50374366, 0.57376713, 0.95487748],
       [0.40471324, 0.93502159, 0.1837735

In [149]:
np.random.randint(1,10)

6

In [160]:
x = np.random.rand(3,3)
print(x)
print(x.max(), x.min())
print(x.argmax())
np.amax(x, axis=0)

[[0.79621404 0.91572381 0.58836559]
 [0.44175579 0.34388512 0.10825358]
 [0.29149504 0.19157269 0.35990164]]
0.9157238109304148 0.10825358196849089
1


array([0.79621404, 0.91572381, 0.58836559])

## Normalize matrix

In [163]:
board = np.random.rand(3,3) * 10
print(board)
np.interp(board, (board.min(), board.max()), (0,1))

[[6.26250954 4.90268854 8.00851324]
 [3.33823824 2.0926581  3.17035268]
 [5.28952053 7.10442682 2.72884895]]


array([[0.7048603 , 0.47499987, 1.        ],
       [0.21054947, 0.        , 0.18217055],
       [0.5403889 , 0.8471757 , 0.10753996]])

In [166]:
(board - board.min()) / (board.max() - board.min())

array([[0.7048603 , 0.47499987, 1.        ],
       [0.21054947, 0.        , 0.18217055],
       [0.5403889 , 0.8471757 , 0.10753996]])

## Mini project

In [17]:
import numpy as np

In [188]:
import numpy as np
def gen_tableau(row, col):
    '''
    row: ligne de tableau
    col: colonne de tableau
    '''
    board = np.arange(row*col) # généralise le tableau de 1 dimension
    np.random.shuffle(board) # une façon de répartir les éléments exists dans la matrice
    board[board <= (0.2*len(board))] = 0 # on va consider tous les indices vaut moin ou inférieur de 20%*len(matrice) affecte 0
    board[board > (0.2*len(board))] = 1 # et les autres indice vaut zero
    board = board.reshape((row,col)) # redimension de matrice 1D à 2D
    print(board)
    #-----------------
    # find matrice carre max
    # remplace 1er col et 1er ligne = 1
    
    board[:, 0][board[:, 0] != 0] = 1
    
    board[0,:][board[0,:] != 0] = 1
    
    for shift_down in range(0,7):
        
        for shift_right in range(0,7):
            
            matrice_2 = board[shift_down:shift_down+2,shift_right:shift_right+2].ravel()[:-1]
            
            min_ = min(matrice_2)
            
            if board[shift_down:shift_down+2,shift_right:shift_right+2][1,1] == 0: continue
                
            elif max(matrice_2) == 0: continue
                
            else:
                
                board[shift_down:shift_down+2,shift_right:shift_right+2][1,1] = min_ + 1
        
    return board

boardRef = gen_tableau(8,8)

boardRef

[[1 0 1 1 0 0 0 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]
 [0 0 0 1 1 1 0 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 0 0 0 1]]


array([[1, 0, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 2, 1, 1, 1, 1],
       [1, 2, 2, 2, 2, 2, 2, 2],
       [1, 2, 3, 3, 3, 3, 3, 3],
       [1, 2, 3, 0, 1, 2, 3, 4],
       [0, 0, 0, 1, 1, 2, 0, 1],
       [1, 1, 1, 0, 1, 2, 1, 1],
       [1, 2, 2, 1, 0, 0, 0, 1]])

In [189]:
boardRef.argmax()

39

In [190]:
print(boardRef.shape) # attribut 'shape' de l'objet np.ndarray
np.unravel_index(boardRef.argmax(), boardRef.shape) # renvoie l'index de posision de objet 

(8, 8)


(4, 7)

In [192]:
board = boardRef.copy()

In [193]:
coord_max = np.unravel_index(boardRef.argmax(), boardRef.shape)
value_max = board.max()
print(f'coord_max: {coord_max} \nvalue_max: {value_max}')

coord_max: (4, 7) 
value_max: 4


In [196]:
board[coord_max[0] - value_max + 1 : coord_max[0] + 1, coord_max[1]-value_max + 1 : coord_max[1] + 1] = -1
board

array([[ 1,  0,  1,  1,  0,  0,  0,  1],
       [ 1,  1,  1,  2, -1, -1, -1, -1],
       [ 1,  2,  2,  2, -1, -1, -1, -1],
       [ 1,  2,  3,  3, -1, -1, -1, -1],
       [ 1,  2,  3,  0, -1, -1, -1, -1],
       [ 0,  0,  0,  1,  1,  2,  0,  1],
       [ 1,  1,  1,  0,  1,  2,  1,  1],
       [ 1,  2,  2,  1,  0,  0,  0,  1]])

In [222]:
def formatter(value):
    if value == 0:
        return 'o'
    elif value == -1:
        return 'x'
    else:
        return '.'
    
f = {'int':formatter} # affecter la fonction dans la dictionaire => callable
f['int'](43)

'.'

In [221]:
print(np.array2string(board, formatter={'int': formatter}))

[[. o . . o o o .]
 [. . . . x x x x]
 [. . . . x x x x]
 [. . . . x x x x]
 [. . . o x x x x]
 [o o o . . . o .]
 [. . . o . . . .]
 [. . . . o o o .]]


In [162]:
def init_board(length):
    basic_board = np.arange(length*length)
    np.random.shuffle(basic_board)
    basic_board[basic_board <= (0.2*len(basic_board))] = 1
    basic_board[basic_board > (0.2*len(basic_board))] = 0
    board = basic_board.reshape((length,length))
    board[board == 1] = - 1
    board = board + 1
    for pos_y in range(length):
            for pos_x in range(length):
                if pos_y != 0 and pos_x != 0 and board[pos_y, pos_x] != 0:
                    val_min = min(board[pos_y - 1][pos_x],
                                 board[pos_y][pos_x - 1],
                                 board[pos_y - 1][pos_x - 1])
                    board[pos_y][pos_x] = val_min + 1
                    
    return board

board = init_board(8)
print(board)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 1 1 0 1 0 1]
 [1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 1 1 0 1]]

[[1 1 1 1 1 1 1 1]
 [1 2 1 1 1 1 1 1]
 [1 1 2 1 0 1 1 1]
 [1 0 0 1 1 0 1 0]
 [0 0 1 1 1 1 1 1]
 [1 1 1 1 1 2 1 1]
 [1 1 1 0 1 1 2 1]
 [0 1 1 1 0 0 1 2]]


## Solution de prof:

In [60]:
board = np.array(np.random.rand(10,10) < 0.2, dtype=int)
board

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 0]])

In [ ]:
board[::1,]