In [12]:
import numpy as np

In [14]:
np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
x = np.zeros(10)
x.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
x = np.zeros(10, int)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
x = np.zeros(10, dtype='int')
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
x = np.zeros(10, dtype=np.int16)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [22]:
board = np.repeat(np.array([1]), 100)
board

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
x = np.ones(100)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.full(100, 1, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [32]:
np.array(range(101))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [33]:
np.ndarray((10, 10), buffer=np.arange(100), dtype= int)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
a = np.arange(100)
a.reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
np.arange(100).reshape(10, 10)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
x = np.arange(100).reshape((10, 10))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
np.arange(10)[::-1]

array([0, 2, 4, 6, 8])

In [40]:
np.flip(np.arange(0, 10), 0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
board = np.arange(10)
board[5:] = 1
board

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])

In [65]:
np.arange(10)[5:-2]

array([5, 6, 7])

In [67]:
np.array([
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [78]:
board = np.zeros((10, 10), int)
board[::2, 1::2] = 1
board[1::2, ::2] = 1
board

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [82]:
np.arange(100).reshape((10, 10)) + 1 * 2 

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19],
       [ 21,  23,  25,  27,  29,  31,  33,  35,  37,  39],
       [ 41,  43,  45,  47,  49,  51,  53,  55,  57,  59],
       [ 61,  63,  65,  67,  69,  71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89,  91,  93,  95,  97,  99],
       [101, 103, 105, 107, 109, 111, 113, 115, 117, 119],
       [121, 123, 125, 127, 129, 131, 133, 135, 137, 139],
       [141, 143, 145, 147, 149, 151, 153, 155, 157, 159],
       [161, 163, 165, 167, 169, 171, 173, 175, 177, 179],
       [181, 183, 185, 187, 189, 191, 193, 195, 197, 199]])

In [92]:
board = np.random.rand(3,3)
print('max of board:', board.max())
print('min of board:', board.min())
board

max of board: 0.9983588303039415
min of board: 0.20735238016094582


array([[0.31109164, 0.40640855, 0.42901823],
       [0.967728  , 0.80408979, 0.82166544],
       [0.99835883, 0.30587498, 0.20735238]])

In [93]:
np.arange(10)[::-1].argmax()

0

In [95]:
board = np.random.rand(3, 3) * 10
print(board)
np.interp(board, (board.min(), board.max()), (0, 1))

[[1.63708018 3.66078639 9.1428112 ]
 [3.07334235 3.42368573 9.62590362]
 [5.34105978 1.79421342 8.05191629]]


array([[0.        , 0.25331718, 0.93952896],
       [0.17978394, 0.22363813, 1.        ],
       [0.46364519, 0.01966914, 0.80297633]])

In [97]:
print('min:',board.min(), '\nmax:', board.max(), '\necart:', board.max() - board.min())

min: 1.6370801775377986 
max: 9.62590362316139 
ecart: 7.988823445623591


In [98]:
(board - board.min()) / (board.max() - board.min())

array([[0.        , 0.25331718, 0.93952896],
       [0.17978394, 0.22363813, 1.        ],
       [0.46364519, 0.01966914, 0.80297633]])

In [ ]:
[[. o o . . o . . . o]
 [. . . . . . . . . .]
 [. . . . . . . . . .]
 [. . . . o . . o . o]
 [. . . . . . . o . .]
 [. . . . o . . . . .]
 [. . . . . . o . . o]
 [. . . . . . . . o .]
 [o . . . . . o . . .]
 [. . . . . o . o . .]]

In [115]:
board = np.arange(10)
# board[board ] = 0
board % 2 == 1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [116]:
np.random.choice((1,0),(10,10),p=[0.2,0.8])

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [117]:
import random

def createMap(size, prob) :
  result = np.random.choice((".", "O"), size * size, p=[1 - prob, prob]).reshape(size, size)
  return result

print(createMap(10, 0.2))

[['.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' 'O' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' 'O' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' 'O' '.' '.']
 ['.' '.' '.' 'O' '.' '.' '.' '.' '.' 'O']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' 'O' '.' '.' '.' '.' 'O' '.' '.' '.']
 ['O' '.' '.' '.' '.' '.' '.' 'O' '.' '.']
 ['.' '.' '.' '.' '.' '.' 'O' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' 'O' '.' '.']]


In [118]:
def gen_tableau(row, col):
    '''
    row: ligne de tableau
    col: colonne de tableau
    '''
    board = np.arange(row*col) # généralise le tableau de 1 dimension
    np.random.shuffle(board) # une façon de répartir les éléments exists dans la matrice
    board[board <= (0.2*len(board))] = 1 # on va consider tous les indices vaut moin ou inférieur de 20%*len(matrice) affecte 0
    board[board > (0.2*len(board))] = 0 # et les autres indice vaut zero
    return board.reshape((row,col)) # redimension de matrice 1D à 2D
tableau = gen_tableau(8,8)
tableau

array([[0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]])

In [120]:
board80 = np.zeros(80).reshape(8, 10)
board80

board20 = np.ones(20).reshape(2, 10)

board = np.concatenate((board80, board20))

b1d = board.ravel()
np.random.shuffle(b1d)

blast = b1d.reshape(10,10)
blast

array([[0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.]])

In [123]:
board = np.array(np.random.rand(10, 10) < 0.2, dtype = int)
board[board == 1] = -1
board

array([[ 0,  0, -1, -1,  0,  0,  0,  0,  0,  0],
       [ 0, -1, -1,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0, -1,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0, -1,  0,  0]])

In [136]:
def init_board(length):
    basic_board = np.arange(length*length)
    np.random.shuffle(basic_board)
    basic_board[basic_board <= (0.2*len(basic_board))] = 1
    basic_board[basic_board > (0.2*len(basic_board))] = 0
    board = basic_board.reshape((length,length))
    board[board == 1] = - 1
    board = board + 1
    for pos_y in range(length):
            for pos_x in range(length):
                if pos_y != 0 and pos_x != 0 and board[pos_y, pos_x] != 0:
                    val_min = min([board[pos_y - 1][pos_x],
                                 board[pos_y][pos_x - 1],
                                 board[pos_y - 1][pos_x - 1]])
                    board[pos_y][pos_x] = val_min + 1
                    
    return board

boardRef = init_board(8)
print(boardRef)

[[1 1 1 1 0 1 1 0]
 [0 1 2 0 1 1 2 1]
 [1 1 2 1 1 2 2 2]
 [1 2 2 2 2 2 3 0]
 [1 2 3 3 3 3 3 0]
 [1 2 3 4 0 1 2 0]
 [1 2 0 1 1 1 2 0]
 [1 0 1 1 2 2 0 0]]


In [137]:
boardRef.argmax()

43

In [138]:
boardRef.shape # attribut 'shape' de l'objet np.ndarray

(8, 8)

In [139]:
np.unravel_index(boardRef.argmax(), boardRef.shape)

(5, 3)

[[1 1 1 1 0 1 1 0]
 [0 1 2 0 1 1 2 1]
 [1 1 2 1 1 2 2 2]
 [1 2 2 2 2 2 3 0]
 [1 2 3 3 3 3 3 0]
 [1 2 3 4 0 1 2 0]
 [1 2 0 1 1 1 2 0]
 [1 0 1 1 2 2 0 0]]

In [141]:
board = boardRef.copy()

In [142]:
coord_max = np.unravel_index(board.argmax(), board.shape)
value_max = board.max()
print('coord_max:', coord_max,'\nvalue_max:', value_max)

coord_max: (5, 3) 
value_max: 4


In [143]:
board[
    coord_max[0] - value_max + 1:coord_max[0] + 1,
    coord_max[1] - value_max + 1:coord_max[1] + 1
] = -1
board

array([[ 1,  1,  1,  1,  0,  1,  1,  0],
       [ 0,  1,  2,  0,  1,  1,  2,  1],
       [-1, -1, -1, -1,  1,  2,  2,  2],
       [-1, -1, -1, -1,  2,  2,  3,  0],
       [-1, -1, -1, -1,  3,  3,  3,  0],
       [-1, -1, -1, -1,  0,  1,  2,  0],
       [ 1,  2,  0,  1,  1,  1,  2,  0],
       [ 1,  0,  1,  1,  2,  2,  0,  0]])

In [151]:
def formatter(value):
   if value == -1:
       return 'x'
   elif value == 0:
       return 'o'
   else:
       return '.'

f = {'int':formatter}
f['int'](43)

'.'

In [148]:
print(np.array2string(board, formatter = {'int':formatter}))

[[. . . . o . . o]
 [o . . o . . . .]
 [x x x x . . . .]
 [x x x x . . . o]
 [x x x x . . . o]
 [x x x x o . . o]
 [. . o . . . . o]
 [. o . . . . o o]]
